import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ShoppingCartContextProvideer } from "@/context/ShopingCartContext";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark:bg-gray-950 dark:text-white">
        <ShoppingCartContextProvideer>
          <Navbar />
          {children}
          <Footer />
        </ShoppingCartContextProvideer>
      </body>
    </html>
  );
}
